version: "3"

services:
  app:
    build:
      dockerfile: ./images/hipsterfy/Dockerfile
      context: .
    entrypoint: "/usr/local/bin/hipsterfy"
    command: [
      "--port=${HIPSTERFY_ADDR_PORT}",
      "--db=postgresql://${HIPSTERFY_DB_USER}:${HIPSTERFY_DB_PASSWORD}@db:5432/${HIPSTERFY_DB_USER}",
      "--spotify_client_id=${HIPSTERFY_SPOTIFY_CLIENT_ID}",
      "--spotify_client_secret=${HIPSTERFY_SPOTIFY_CLIENT_SECRET}",
      "--spotify_redirect_uri=${HIPSTERFY_SPOTIFY_REDIRECT_URI}",
      "--faktory_host=jobqueue",
      "--faktory_port=7419",
      "--faktory_password=${HIPSTERFY_JOBQUEUE_PASSWORD}",
      "--zipkin_host=tracing",
      "--zipkin_port=9411",
      "--health_secret=foo",
      "--pod_name=local-docker-compose"
    ]
    ports:
      - "${HIPSTERFY_ADDR_PORT}:${HIPSTERFY_ADDR_PORT}"
    depends_on:
      - db
      - jobqueue
      - tracing

  worker:
    build:
      dockerfile: ./images/hipsterfy/Dockerfile
      context: .
    entrypoint: "/usr/local/bin/hipsterfy-worker"
    command: [
      "--db=postgresql://${HIPSTERFY_DB_USER}:${HIPSTERFY_DB_PASSWORD}@db:5432/${HIPSTERFY_DB_USER}",
      "--spotify_client_id=${HIPSTERFY_SPOTIFY_CLIENT_ID}",
      "--spotify_client_secret=${HIPSTERFY_SPOTIFY_CLIENT_SECRET}",
      "--faktory_host=jobqueue",
      "--faktory_port=7419",
      "--faktory_password=${HIPSTERFY_JOBQUEUE_PASSWORD}",
      "--zipkin_host=tracing",
      "--zipkin_port=9411"
    ]
    depends_on:
      - db
      - jobqueue
      - tracing

  db:
    build:
      dockerfile: ./images/hipsterfy-db/Dockerfile
      context: .
    environment:
      POSTGRES_USER: ${HIPSTERFY_DB_USER}
      POSTGRES_PASSWORD: ${HIPSTERFY_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "hipsterfy-db-data:/var/lib/postgresql/data"

  jobqueue:
    image: contribsys/faktory:1.4.0
    entrypoint: "/faktory"
    command: [
      "-b", ":7419",
      "-w", ":7420",
      "-e", "production"
    ]
    environment:
      FAKTORY_PASSWORD: ${HIPSTERFY_JOBQUEUE_PASSWORD}
    ports:
      - "7419:7419"
      - "7420:7420"
    volumes:
      - "hipsterfy-jobqueue-data:/var/lib/faktory"

  tracing:
    image: jaegertracing/all-in-one:1.18
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "9411:9411"
      - "16686:16686"

volumes:
  hipsterfy-db-data:
  hipsterfy-jobqueue-data:
