version: "3"

services:
  app:
    build:
      dockerfile: ./images/hipsterfy/Dockerfile
      context: .
    entrypoint: "/usr/local/bin/hipsterfy"
    command: [
      "--host=${HIPSTERFY_ADDR_HOST}",
      "--port=${HIPSTERFY_ADDR_PORT}",
      "--client_id=${HIPSTERFY_SPOTIFY_CLIENT_ID}",
      "--client_secret=${HIPSTERFY_SPOTIFY_CLIENT_SECRET}",
      "--db=postgresql://${HIPSTERFY_DB_USER}:${HIPSTERFY_DB_PASSWORD}@db:5432/${HIPSTERFY_DB_USER}",
      "--faktory_host=jobqueue",
      "--faktory_port=7419",
      "--faktory_password=${HIPSTERFY_JOBQUEUE_PASSWORD}"
    ]
    ports:
      - "${HIPSTERFY_ADDR_PORT}:${HIPSTERFY_ADDR_PORT}"
    depends_on:
      - db
      - jobqueue

  worker:
    build:
      dockerfile: ./images/hipsterfy/Dockerfile
      context: .
    entrypoint: "/usr/local/bin/hipsterfy-worker"
    command: [
      "--client_id=${HIPSTERFY_SPOTIFY_CLIENT_ID}",
      "--client_secret=${HIPSTERFY_SPOTIFY_CLIENT_SECRET}",
      "--db=postgresql://${HIPSTERFY_DB_USER}:${HIPSTERFY_DB_PASSWORD}@db:5432/${HIPSTERFY_DB_USER}",
      "--faktory_host=jobqueue",
      "--faktory_port=7419",
      "--faktory_password=${HIPSTERFY_JOBQUEUE_PASSWORD}"
    ]
    depends_on:
      - db
      - jobqueue

  db:
    build:
      dockerfile: ./images/hipsterfy-db/Dockerfile
      context: .
    environment:
      POSTGRES_USER: ${HIPSTERFY_DB_USER}
      POSTGRES_PASSWORD: ${HIPSTERFY_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "hipsterfy-db-data:/var/lib/postgresql/data"

  jobqueue:
    image: contribsys/faktory:1.4.0
    entrypoint: "/faktory"
    command: [
      "-b", ":7419",
      "-w", ":7420",
      "-e", "production"
    ]
    environment:
      FAKTORY_PASSWORD: ${HIPSTERFY_JOBQUEUE_PASSWORD}
    ports:
      - "7419:7419"
      - "7420:7420"
    volumes:
      - "hipsterfy-jobqueue-data:/var/lib/faktory"

volumes:
  hipsterfy-db-data:
  hipsterfy-jobqueue-data:
